### PR TITLE
Added Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by luxdev01**

### CODE REVIEW

**Comment by StellarSand** [comment]
Hello, thanks a lot for the translations!
I'd appreciate if you could also translate the feedback strings to Brazilian Portuguese.

Create a new file named `messages_pt_rBR.properties` in [res/raw](https://github.com/StellarSand/IYPS/tree/main/app/src/main/res/raw) and translate the [feedback strings](https://github.com/nulab/zxcvbn4j/blob/main/src/main/resources/com/nulabinc/zxcvbn/messages.properties).

**Comment by luxdev01** [comment]
Okay, I'll do that!

**Comment by luxdev01** [comment]
Ready to merge I guess 🫡

**Comment by StellarSand** [comment]
Excellent! Thank you. :)

**Pull request merged**
